import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Arquitetura',
      collapsed: false,
      link: { type: 'generated-index', title: 'Arquitetura', description: 'Visão arquitetural completa do sistema.' },
      items: [{ type: 'autogenerated', dirName: 'arquitetura' }],
    },
    {
      type: 'category',
      label: 'Backend (Go)',
      link: { type: 'generated-index', title: 'Backend BFA', description: 'Serviço Go — API bancária.' },
      items: [{ type: 'autogenerated', dirName: 'backend' }],
    },
    {
      type: 'category',
      label: 'Agente IA (Python)',
      link: { type: 'generated-index', title: 'Agente IA', description: 'Agente inteligente com RAG.' },
      items: [{ type: 'autogenerated', dirName: 'agente' }],
    },
    {
      type: 'category',
      label: 'Frontend (React Native)',
      link: { type: 'generated-index', title: 'Frontend Web', description: 'App mobile-first com Expo.' },
      items: [{ type: 'autogenerated', dirName: 'frontend' }],
    },
    {
      type: 'category',
      label: 'API',
      link: { type: 'generated-index', title: 'API Reference', description: 'Contratos e endpoints da API.' },
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
    {
      type: 'category',
      label: 'DevOps & Infra',
      link: { type: 'generated-index', title: 'DevOps & Infra', description: 'CI/CD, Docker, deploy.' },
      items: [{ type: 'autogenerated', dirName: 'devops' }],
    },
    {
      type: 'category',
      label: 'Guias',
      link: { type: 'generated-index', title: 'Guias', description: 'Tutoriais e guias práticos.' },
      items: [{ type: 'autogenerated', dirName: 'guias' }],
    },
  ],
};

export default sidebars;
